(function_definition) @fold
(class_definition) @fold
(if_statement) @fold
(for_statement) @fold
(while_statement) @fold
(try_statement) @fold
(with_statement) @fold
(match_statement) @fold
(list) @fold
(dictionary) @fold
(string) @fold
